#!/bin/sh -e

export PREFIX=""
if [ "$VIRTUAL_ENV" != '' ]; then
    export PREFIX="$VIRTUAL_ENV/bin/"
elif [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi
export SOURCE_FILES="dymmond_settings tests"
export EXCLUDE=__init__.py
export MAIN="dymmond_settings"

set -x

${PREFIX}mypy $MAIN
${PREFIX}ruff check $SOURCE_FILES --line-length 99
${PREFIX}black $SOURCE_FILES --check --diff --check --line-length 99
${PREFIX}isort $SOURCE_FILES --check --diff --project=dymmond_settings --line-length 99
