#!/bin/sh -e

export PREFIX=""
if [ "$VIRTUAL_ENV" != '' ]; then
    export PREFIX="$VIRTUAL_ENV/bin/"
elif [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

export SOURCE_FILES="dymmond_settings tests"
set -x

${PREFIX}ruff check $SOURCE_FILES --fix --line-length 99
${PREFIX}black $SOURCE_FILES --line-length 99
${PREFIX}isort $SOURCE_FILES --project=dymmond_settings --line-length 99
${PREFIX}mypy dymmond_settings
